version: "3.7"

x-homelinksink-defaults: &homelinksink-defaults
  restart: unless-stopped
  image: homelinksink:latest
  ulimits:
    nproc: 65535
    nofile:
      soft: 262144
      hard: 262144

services:
  homelink-sink:
    <<: *homelinksink-defaults
    container_name: homelink-sink
    ports:
      - 1433:1433
    volumes:
      - "./src/env:/etc/homelink-sink/env"
    environment:
      - NODE_ENV=propduction